name: 'edutrack'
version: '1.0.0'
config-version: 2

profile: 'edutrack'

# model-paths: ["models"]

# models:

#   edutrack:

#     staging:
#       +schema: dbt_demo_stg
#       +materialized: table

#     intermediate:
#       +schema: dbt_demo_int
#       +materialized: table

#     marts:
#       +schema: dbt_demo_prod
#       +materialized: table