SELECT
    TRIM(ATTENDANCE_ID) AS ATTENDANCE_ID,
    TRIM(SCHOLAR_ID) AS SCHOLAR_ID,
    ATTENDANCE_DATE,
    UPPER(TRIM(STATUS)) AS STATUS,
    CHECK_IN_TIME,
    CREATED_AT

FROM {{ source('edutrack', 'attendance') }}

WHERE ATTENDANCE_ID IS NOT NULL