SELECT
    TRIM(SCHOLAR_ID) AS SCHOLAR_ID,
    INITCAP(TRIM(SCHOLAR_NAME)) AS SCHOLAR_NAME,
    TRIM(SCHOOL_ID) AS SCHOOL_ID,
    TRIM(CLASS) AS CLASS,
    DATE_OF_BIRTH,
    UPPER(TRIM(GENDER)) AS GENDER,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    ADMISSION_DATE,
    CREATED_AT

FROM {{ source('edutrack', 'scholar') }}

WHERE SCHOLAR_ID IS NOT NULL