SELECT
    TRIM(SCHOOL_ID) AS SCHOOL_ID,
    INITCAP(TRIM(SCHOOL_NAME)) AS SCHOOL_NAME,
    INITCAP(TRIM(CITY)) AS CITY,
    INITCAP(TRIM(STATE)) AS STATE,
    UPPER(TRIM(SCHOOL_TYPE)) AS SCHOOL_TYPE,
    CREATED_AT

FROM {{ source('edutrack', 'school') }}

WHERE SCHOOL_ID IS NOT NULL